version: '3.8'

services:
  redis:
    image: bitnami/redis:6.2
    container_name: taskqueue-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
      - redis_config:/bitnami/redis/conf
    networks:
      - taskqueue-network

volumes:
  redis_data:
    driver: local
  redis_config:
    driver: local

networks:
  taskqueue-network:
    driver: bridge 